### ISSUE TITLE
Question about patterns

### ISSUE THREAD

**Issue by Sile25** [GregoryMorse/trendln#12]
First of all, i wanted to thank you for taking your time to make the article (i found this repository there) and to release this awesome library, it's incredibly useful and i'm learning a lot from it.

Before finding your article, i was dealing with a quite complicated task: detecting patterns from OHLC data, such as flags, pennants, double bottoms and so on.
Just like you did, i started from computing local minima and maxima from my data, to do that i used the following function:
`df['max'] = df.iloc[argrelextrema(df.Open.values, np.greater_equal, order=n)[0]]['Open']`

where `df` is the dataframe that will store the OHLC data. From there i've been defining patterns on my own, now i'm trying to learn pattern detection to try and find patterns defined by me on other dataset, but i'm ecountering a lot of problems. I was wondering if you are planning to cover that part too on your library, or if you have any tip on how to do that. Keep up your awesome work.

**Comment by GregoryMorse** [comment]
Thanks for the feedback!  Yes I did want to do a lot of these patterns.  The rectangular patterns are actually not so difficult I anticipate.  However this might need to consider 2 point lines which there are a lot of, and then use something the along the line of an O(n^2) comparing all lines to all other lines with extra weight for lines with more points.  In the end the intersection of the lines must be computed and then the proximity of the intersection to points in the data.

For pattern detection, its best to come up with very general ideas and relate it to sound and efficient mathematical techniques but its more time consuming to do a nice solution in this way.

The real interesting computational geometry is in patterns like head and shoulder or cup and handle.  This requires finding circular or elliptical arc and since a circle is defined by 3 points and an ellipse by 5, its more complex.  However there are ways of using the Hough transform to detect these sorts of shapes.  I have some ideas and I did want to do this and add it to the library.  Currently I had added a whole OHLC candlestick recognition set of patterns to identify single or multi-day candlestick patterns in a comprehensive and elegant way.  That is probably the next article.  Have been busy though needless to say.

**Comment by Sile25** [comment]
This is fair enough! Another thing that i loved about your article is finally applying mathematical concepts such as derivatives and integrals. I have a decent mathematical background while i'm less skilled with programming and i always wanted to see those concepts applied to trading data, and i didn't see a lot of sources about this until now. Keeping a close eye on this library!

EDIT: One last thing: is there any way to get only horizontal supports and resistances, when dealing with trendlines?
